apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bvbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bvbs
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bvbs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bvbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bvbs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ubui-tenant/rhtap-demo-app/hacbs-test-project-bvbs@sha256:20d10ab2b29f459aed9255b1eacfbc7c57da7e3c79049d259d2aca26898758f3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
